### ISSUE TITLE
iOS not supported in the podspec

### ISSUE THREAD

**Issue by Andrew-Lees11** [IBM-Swift/BlueRSA#27]
When trying to use the BlueRSA pod for iOS I get the following error:

```
The platform of the target `CocoapodsTest` (iOS 12.0) is not compatible with `BlueRSA (1.0.17)`, which does not support `ios`
```
when comparing the podspec of BlueRSA to [BlueCryptor](https://github.com/IBM-Swift/BlueCryptor/blob/master/BlueCryptor.podspec) I saw that:
```
s.ios.deployment_target = "10.0"
```
Was missing. In the readme it states the BlueRSA runs on iOS 10 or higher so I would expect this to work. 

There is not a reference to the BlueRSA [pod](https://cocoapods.org/pods/BlueRSA) but I assume it is intended to support this?

**Comment by peterpaulis** [comment]
+1

**Comment by peterpaulis** [comment]
for now you can use     

`pod 'BlueRSA', :git => 'https://github.com/peterpaulis/BlueRSA.git'`

**Comment by billabt** [comment]
Fixed in version _1.0.19_.

**Comment by billabt** [comment]
Need to provide a framework target.  Re-opening.

**Comment by billabt** [comment]
Fixed in version _1.0.20_.

**Comment by failynsedik** [comment]
> for now you can use
> 
> `pod 'BlueRSA', :git => 'https://github.com/peterpaulis/BlueRSA.git'`

We can't update our minimum deployment target yet, so this is what I did for now. Thanks for this!
