### ISSUE TITLE
Crash while creating private key with Base64 string on Linux

### ISSUE THREAD

**Issue by Luzanov** [IBM-Swift/BlueRSA#38]
I removed header and footer lines in my private key file and use:

`let privateKey = try CryptorRSA.createPrivateKey(withBase64: base64String)`

it works well on Mac OS but on Linux it crashes with error:

Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by Andrew-Lees11** [comment]
@Luzanov 
Would you be able to create a dummy private key and post it here so I can try and recreate the crash?
Alternatively could you ASN1 [decode your key here](https://lapo.it/asn1js/) and let me know what structure it has?

**Comment by Luzanov** [comment]
@Andrew-Lees11 this is my private key without header and footer lines:
`MIIJJwIBAAKCAgEAlR5b4qvWa/3OdkN8r4aoPaIdAryPc5hfNHXf7imZQKzU1LfQde+HICPYp1lBBxDPrEIT3QBjo+EX4l/2AiUXagyVfnQKGwy5un93CMdjRmWuqoCQ1KHxaM2Qb9NFvY+5qAqv+vX3Qdy8KK76x1zfectxWPRA1ql/6yJV4US939aZKrv46mUiyAfhmLMNspxe0Q63+qTj2GvHiv3KvR6/7HjwzBq54eU8ivZdK/3i+jlqNGorDhTsHOfDhXzHFTfYLKvA6aLQ6+SrTKHzSD7DfEPTAN5fhdZeWCP4b/EegokCItFZhSj6hVj2+9TFDU5JvOofljJHfXn5bjWGurvn3f3HP/bVGHa5ndDEjUobXatHD9oSNb9+gGQGqITwNB1BMZlH7opJ70oU8UJfqVCXHNMr8EhrEh4G1oZ3AYomFUorS5+DjRLWK8jCbJDRcAlyxa2hI5N9aG23Ilz2u7hlkKdHmmdid+98uc9v9oJi64oNo3Q4wsTE1sYkEXGOmvO7hAIW1InNUhKBiB/aTmeua78iMQIVooUukPEUlnqe7z8QsbxzyUx7KgkpfyfTQUcuHu2dsgxUgb2XAuVSqB+sAHhOmQxjzWSaywg8BVgVxqT45OBKzK6GSU5Ep/H5tPMhqJQ5mnFXq3cIyLv8UT3imd9/jSsfyGl6IkEOZdwkfc8CAwEAAQKCAgBBGJ8xHSW+P+6c5worz+NrAHWcp7cR1d8d1iVa4TMDLk+8yr+IdHevGqbuK0L9dCPMhY4JSK22sUFNc+m/dvS5OWQbb0moFE6R8SoEHZKjfSkaSoSvJkDuKOrYPkkwHumDx6KaMjztthA3zGcyl8MA9sR0+i/B5f2vJm6KKAmhiRuVMbjQjjT4UKR1lhixM50as0uycb/7TtWtwev60k0jTIqF91bVG87ptPHoje1DocPQvNYt0Alg9vX+NIHuK9JFcfcFpyuABvOWwQ4kqC2LdkpLE0hs8y99V7qRF5fjkS7rBywGuuReSP+M4Q3iqJ39B9GhLjLSPmiaaWh25SerMQzpygXXSW7nHVrdNwWKNgknrENFHh3EkQA3gpl+Gn9gKWsowN9W9b1I1V3g/TF81lxyaChbms5fU/QygBV/K2NeLoP9ACrVtiqBL6AdYxImlbxTHNh4fmYsK8zk1/HtsYTFwkLMIqE8DLyypqHtXHsGE2BHqs1Rd/AVhgQ22UXMXrjbku8S6VioJEAjJ6iJH3/oUgGv9CZJ8gjQqOQGBHf0ztNQr0YA30e5KRNCHu8brjSWmfr8Q6OtQDay3FtCTc5P7DSrXRfzuQPsoLvKe25Ad0kX6bRiYTgcz+ZYHXcqkAn5tY4yIf05JLauFG0ob5e1qE1npoKUZj5Y1njiVQKCAQEAxrtyaF+Mo+kIRra1XWLUh3jp/V+u6ZFsOwwsg21Ud8xMb+YAWZBnnZCdFAx/OmSS6n4xULYGP1VjGdDsMYP5RoDIyZGibp12Htk5qXvzKCvGHBwTWBpNu0XouIXUg+zSoetvfqhdeIkOFly39skHiGrE+cWVV34llvNZKrylWlSSeVtEB3q9ouwG3zomDfrWjhw16Xv6kCuhSPPgBkGELRyy1NNqBbjcrIv2L+CGVevo9TjAyO557euZ1sN9wEtc3HR199qroWnciSN/7s5ipmWpl4s05PGtK1duQOYfp8JeXPHzIPkSzzoa8vIGfbQJFgJgVDC/9CAaNf6z75/GawKCAQEAwBblQYt4fkIboydTszIjUtCv8fDMJNzRhpvM257dqPEsb1cXv9gKOcKWwf0UqhP4yAm9Hm/EnERvbRm01GqewXV6zALXelCOrUu8g9QhPJHbRYZKaAhmKWxiNW0XCKxAKYhuZ3VESeLR6LwhniHEaoEUoy/0Yvj5xNL1L2/LszGSSBpoL7ndSGrrzXBieps5PaGElqpF5F/0fYPEJK0aCC11MiLQCzLr39n61aoR8oOH36sZ/7AL+/+2EKPe5kcSsIxHHAdjfPtQ/0e3a66hr1nqZKp2+N9225oDLzPlAW6HOf/xA7ZSUmvuYKhyVgdbOL01t0nNgTggwmaVp3EXLQKCAQArs9T49uoqsXhMdKl1m+I42HI8ceo5Gu2+HnM7g7NrlNXKVb4F9CeVEtQ4MHdaE/vq7U1S/nRpQRHF/5exW+BZjMCa8xfRU3dCWWrAxq02TEoIrHPkkARABqOi0Gtnh5DaYrfmFohXlWwvprwd3R929GPUuYqZ7ve9Nk6Jg2qpbqe3YEaZjnhdd6IbPOJZeKvuHG4OpmD3i2CwdlDxjz7N3N3Gx6ctEvYUS8MbzDg+dN6J7q0Wgrr1gzYVcHAa9Xe6UzIOC1xq5qjEz7W2glRXW0vsM4SyRCNcwKFSTEjxz2CI9/wLaDqmr5R1kJu00P6ehG9ClGXh/Z1F+nj/XRd5AoIBAEGXD80jvI8QL7O0OAZWNm2OyKVKXcqwg/L8vCS5yGJph4y1Jmzhbgxu/19Z9XZlv2s+uA7uhyn8zDdqsa5egbr5TGbhCYbAfxd5ZvN0uaye+UpyInIHfCrk0VwA1f6mInqMFXbKOfkotBhONQRz70eWr99Q/pfVACRPDF2YROv5H0PzkGPLiV2y9LV/jIDlA9ShlE6F8bubcDZzicQkP2FPdFccQAGy74vOOLJAkkRG2VxsZkJCcLUpiZeA/RmQZzdVjuppM3V3sx6X9G+Wf6sKftjExD8SvtkZa8DwbV/hx9bsJ/XmiZGPPSRQIEpz1Jg5M2BUmRFogvceZDd6jDkCggEAHJxM8Uk2tdOhoaW3bdz3fMr/fPyMCChJuOExQabLW32Ypr2KC02I/UhFeX1QOcFnd6jdvX9DNk5osVV8mCqzL0jJbr+2qimGEo5iSiqJRW/SXo7NuN73EqEmtii+5m4sb6JWl7cs8hDwOjzIfJVGbJJmDdvz5vp056/adKLi6INN5FjbL1vx8AG0eB3f552FY+bcBhtIeG+o7WuvLMlClkXW4ol8T9VscQdhGQbyfuprI5SozB0t9YvBFkyI4yuIu+cBQdhHmPUdD2YaDaNGAyrJVLAMZkVuEIpLUMAyXrNBma964Xc1M3YvhspvSD4L6bfpYxaHf33ZBUcR9OeGjw==`

**Comment by Andrew-Lees11** [comment]
I have found the bug and raised PR #39  which fixes this case. 
Once @billabt reviews it we an look at releasing this fix.

**Comment by Andrew-Lees11** [comment]
Closing this issue now the fix has been merged in 1.0.25.
