### ISSUE TITLE
Use of DER in OpenSSL

### ISSUE THREAD

**Issue by gtaban** [IBM-Swift/BlueRSA#7]
Right now when a DER encoded key is being used in OpenSSL, we convert to PEM and then create an RSA object from the PEM data.
OpenSSL has `d2i_PrivateKey_bio` which can be used directly for DER data.

Investigate if it's a good idea to use that instead of only PEM.

**Comment by Andrew-Lees11** [comment]
Closing sine this change was implemented in pr #44 and tagged in  1.0.27
