### ISSUE TITLE
Store EVP key instead of RSA in key.reference

### ISSUE THREAD

**Issue by gtaban** [IBM-Swift/BlueRSA#8]
It is recommended that we use EVP functions instead of RSA and EVP functions take in EVP keys. Right now I am converting the RSA key into EVP every time I want to use to use it. This is inefficient.

```
                // convert RSA key to EVP
                let  evp_key = EVP_PKEY_new()
                EVP_PKEY_set1_RSA(evp_key, key.reference)
```

**Comment by Andrew-Lees11** [comment]
Closing since this this was merged in 1.0.24
